### ISSUE TITLE
empty csv file

### ISSUE THREAD

**Issue by radka-j** [theosanderson/covid_uk_data_timestamped#1]
Hello and thank you so much for maintaining this archive!

I just wanted to flag that the latests csv in `all` is empty (that's the `2020-10-11.csv`). Since the new data tends to get uploaded in the evening, the data available for download now should still be the data that was released yesterday (easily checked by latest `Specimen date` being the 10th). In case you do not manage to get the csv in time - we have downloaded it today morning and are happy to share if you want it. Just let me know :)

**Comment by theosanderson** [comment]
Hey, thanks so much for pointing this out. I was downloading from the location to which the link was redirected and it looks like that has changed, so this would have continued to fail. I've just fixed this and updated so things should (now) be OK. Thanks a lot for raising this and the offer of the data.

Really glad someone is finding this useful!
